# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYDTHhABa15mU0yf_YTIuLNz--Bjbvav
"""

import pandas as pd
import numpy as np
from prophet import Prophet
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt

np.random.seed(42)

dates = pd.date_range(start="2023-01-01", end="2024-12-31", freq="D")

trend = np.linspace(100, 200, len(dates))
weekly = 20 * np.sin(2 * np.pi * dates.dayofweek / 7)
yearly = 30 * np.sin(2 * np.pi * dates.dayofyear / 365)

rain = np.random.binomial(1, 0.3, len(dates))
rain_effect = rain * -40

noise = np.random.normal(0, 15, len(dates))

rides = trend + weekly + yearly + rain_effect + noise

df = pd.DataFrame({
    "ds": dates,
    "y": rides,
    "rain": rain.astype(int)
})

df.head()

split_idx = int(len(df) * 0.8)

train_df = df.iloc[:split_idx]
test_df = df.iloc[split_idx:]

print("Train size:", len(train_df))
print("Test size:", len(test_df))

# Sort data by date
df = df.sort_values("ds")

# Train-test split (80% train, 20% test)
train_size = int(len(df) * 0.8)
train = df.iloc[:train_size]
test = df.iloc[train_size:]

model = Prophet()
model.fit(train)

model = Prophet(interval_width=0.8)

model.fit(train_df)

future_test = test[["ds"]]
forecast_test = model.predict(future_test)

future = model.make_future_dataframe(periods=len(test_df), freq="D")
future["rain"] = df["rain"].values

forecast = model.predict(future)
forecast.tail()

model.plot(forecast)
plt.show()

y_true = test_df["y"].values
y_pred = forecast.iloc[-len(test_df):]["yhat"].values

mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

import pickle

with open("prophet_model.pkl", "wb") as f:
    pickle.dump(model, f)

"""## to download the forecast results"""

forecast_download = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

forecast_download.to_csv('forecast_results.csv', index=False)

from google.colab import files
files.download('forecast_results.csv')

"""## to download the dataframe"""

original_data = df[['ds', 'y', 'rain']]

original_data.to_csv('original_data.csv', index=False)

from google.colab import files
files.download('original_data.csv')